const { test, expect } = require('@playwright/test');
const fs = require('fs');
const path = require('path');
const base = 'http://localhost:3000';
const out = path.resolve('output/b2b-workflow-audit');
const credentials = fs.existsSync('.local/b2b-demo/credentials.json') ? JSON.parse(fs.readFileSync('.local/b2b-demo/credentials.json')) : [];
test.skip(process.env.CERBYL_B2B_AUDIT !== '1' || !credentials.length, 'Local demo audit only; set CERBYL_B2B_AUDIT=1 with demo accounts installed.');
const stamp = Date.now().toString().slice(-7);
const course = 'QA' + stamp;
const assignmentTitle = 'QA — Explain the probability of gold ' + stamp;
const answer = 'There are four equally likely counters altogether: three blue and one gold. Only one is gold, so the probability of choosing gold is 1/4. For a fair six-sided die, the probability of rolling a 2 is 1/6.';
const feedback = 'You correctly counted all four outcomes and found 1/4. Your die example also uses equally likely outcomes correctly. Next, explain what would change if the counter were chosen without looking but the counters had different sizes.';
async function login(browser, role) {
 const context = await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();page.setDefaultTimeout(15000);
 page.on('pageerror', error=>{fs.appendFileSync(out+'/runtime-errors.log',error.message+'\n')});
 const user=credentials.find(c=>c.username===`northstar.${role}`);
 await page.goto(base+'/login');await page.getByLabel('Username',{exact:true}).fill(user.username);await page.getByLabel('Password',{exact:true}).fill(user.password);await page.locator('button[type=submit]').first().click();await page.waitForURL('**/'+(role==='teacher'?'educator':'student'));
 return page;
}
async function shot(page, name) {await page.evaluate(() => Promise.all(document.getAnimations().filter(a => a.effect?.getTiming().iterations !== Infinity).map(a => a.finished.catch(() => {}))));await page.screenshot({path:out+'/screenshots/'+name+'.png',fullPage:true});}

test('real teacher/student workflow, retries, persisted drafts and responsive dialogs', async ({ browser })=>{
 test.setTimeout(180000);fs.mkdirSync(out+'/screenshots',{recursive:true});
 const teacher=await login(browser,'teacher');
 await teacher.goto(base+'/educator/classes');await teacher.getByRole('button',{name:'Create class',exact:true}).click();
 let dialog=teacher.getByRole('dialog');
 await dialog.getByLabel('Course code',{exact:true}).fill(course);await dialog.getByLabel('Course title',{exact:true}).fill('QA Probability foundations');await dialog.getByLabel('Class name',{exact:true}).fill('Workflow audit '+stamp);
 await dialog.getByLabel('Aarav Northstar',{exact:true}).check();await dialog.getByLabel('Riya Northstar',{exact:true}).check();await shot(teacher,'01-teacher-create-class');
 const created=teacher.waitForResponse(r=>r.url().includes('/companies/')&&r.url().endsWith('/sections')&&r.request().method()==='POST');
 await dialog.getByRole('button',{name:'Create class',exact:true}).click();const result=await created;expect(result.status()).toBe(201);const sid=(await result.json()).id;
 await expect(teacher.getByRole('dialog')).toHaveCount(0);await teacher.getByRole('button').filter({hasText:course}).click();dialog=teacher.getByRole('dialog');await dialog.getByRole('button',{name:'Materials',exact:true}).click();
 await dialog.getByLabel('Material title').fill('Probability reference — all equally likely outcomes');
 await dialog.locator('input[type=file]').setInputFiles({name:'probability-foundations.txt',mimeType:'text/plain',buffer:Buffer.from('Probability foundations\n\nA bag contains three blue counters and one gold. When each counter is equally likely to be chosen, P(gold) = favourable outcomes / total outcomes = 1/4. Count the gold counter in the denominator too. For a fair six-sided die, P(2) = 1/6. Random selection and equally likely outcomes are assumptions of this simple counting method.')});
 await dialog.getByRole('button',{name:'Publish material'}).click();await expect(dialog.getByText('Material published to enrolled students.')).toBeVisible();await shot(teacher,'02-teacher-published-material');await dialog.getByRole('button',{name:'Close class workspace'}).click();
 await teacher.goto(base+'/educator/assignments');await teacher.getByRole('button',{name:'New assignment'}).click();dialog=teacher.getByRole('dialog');await dialog.getByRole('combobox',{name:'Class',exact:true}).selectOption(String(sid));await dialog.getByLabel('Assignment title').fill(assignmentTitle);await dialog.getByLabel('Instructions',{exact:true}).fill('A bag contains three blue counters and one gold counter. Each counter is equally likely to be chosen. What is the probability of choosing gold? Explain why your denominator is correct, then give a second example using a fair die.');await dialog.getByLabel('Rubric and success criteria').fill('4 points: counts all four counters. 4 points: probability 1/4 with correct reasoning. 2 points: a correct fair-die example.');await dialog.getByLabel('Points',{exact:true}).fill('10');
 await teacher.setViewportSize({width:390,height:844});await shot(teacher,'03-teacher-assignment-mobile');await expect(dialog.getByRole('button',{name:'Publish assignment'})).toBeInViewport();
 const published=teacher.waitForResponse(r=>r.url().endsWith('/educator/assignments')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'Publish assignment'}).click();const pub=await published;expect(pub.status()).toBe(201);const aid=(await pub.json()).id;await teacher.setViewportSize({width:1440,height:1000});
 const student=await login(browser,'student');await student.goto(base+'/student/library');await student.getByRole('combobox',{name:'Class',exact:true}).selectOption(String(sid));const download=student.waitForEvent('download');await student.getByRole('button',{name:/Download Probability reference/}).click();expect((await download).suggestedFilename()).toBe('probability-foundations.txt');await shot(student,'04-student-study-library');
 await student.goto(base+'/student/assignments');let row=student.locator('article').filter({has:student.getByRole('heading',{name:assignmentTitle})});await row.getByRole('button').first().click();dialog=student.getByRole('dialog');await dialog.getByLabel('Your response').fill(answer);
 await student.route('**/student/assignments/*/draft',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Draft could not be saved. Please retry.'})}));await dialog.getByRole('button',{name:'Save draft',exact:true}).click();await expect(dialog.getByText('Draft could not be saved. Please retry.')).toBeVisible();await expect(dialog.getByLabel('Your response')).toHaveValue(answer);await shot(student,'05-student-draft-failure-preserved');await student.unroute('**/student/assignments/*/draft');await dialog.getByRole('button',{name:'Save draft',exact:true}).click();
 await student.reload();row=student.locator('article').filter({has:student.getByRole('heading',{name:assignmentTitle})});await row.getByRole('button').first().click();dialog=student.getByRole('dialog');await expect(dialog.getByLabel('Your response')).toHaveValue(answer);await student.setViewportSize({width:390,height:844});await shot(student,'06-student-restored-draft-mobile');await expect(dialog.getByRole('button',{name:/Submit work/})).toBeInViewport();await dialog.getByRole('button',{name:/Submit work/}).click();await expect(student.getByRole('dialog')).toHaveCount(0);await student.setViewportSize({width:1440,height:1000});
 await student.goto(base+'/student/messages');await student.getByRole('combobox',{name:'Class',exact:true}).selectOption(String(sid));await student.getByLabel('Recipient').selectOption({index:1});await student.getByLabel('Subject').fill('QA — Checking equally likely outcomes');await student.getByLabel('Message',{exact:true}).fill('I counted all four counters. Is equally likely selection the reason I can use favourable outcomes divided by total outcomes?');await student.getByRole('button',{name:'Send privately'}).click();await expect(student.getByText('Private message sent.')).toBeVisible();await shot(student,'07-student-message-sent');
 await teacher.goto(base+'/educator/messages');await teacher.getByRole('combobox',{name:'Class',exact:true}).selectOption(String(sid));await expect(teacher.getByText('QA — Checking equally likely outcomes')).toBeVisible();await shot(teacher,'08-teacher-received-message');
 await teacher.goto(base+'/educator/assignments');row=teacher.locator('article').filter({has:teacher.getByRole('heading',{name:assignmentTitle})});await row.getByRole('button',{name:/Review/}).click();dialog=teacher.getByRole('dialog');let learner=dialog.locator('article').filter({hasText:'Aarav Northstar'}).first();await expect(learner.getByText(answer,{exact:true})).toBeVisible();await learner.getByLabel('Score / 10').fill('10');await learner.getByRole('textbox',{name:'Feedback',exact:true}).fill(feedback);
 await teacher.route('**/submissions/*/grade',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'Feedback could not be published. Please retry.'})}));await learner.getByRole('button',{name:'Publish grade'}).click();await expect(dialog.getByText('Feedback could not be published. Please retry.')).toBeVisible();await expect(learner.getByRole('textbox',{name:'Feedback',exact:true})).toHaveValue(feedback);await shot(teacher,'09-teacher-grade-failure-preserved');await teacher.unroute('**/submissions/*/grade');await learner.getByRole('button',{name:'Publish grade'}).click();await expect(learner.getByRole('button',{name:'Update grade'})).toBeVisible();await shot(teacher,'10-teacher-published-feedback');
 await student.goto(base+'/student/assignments');row=student.locator('article').filter({has:student.getByRole('heading',{name:assignmentTitle})});await row.getByRole('button').first().click();await expect(student.getByText(feedback,{exact:true}).first()).toBeVisible();await shot(student,'11-student-feedback');
 await teacher.goto(base+'/educator/messages');await teacher.getByRole('link',{name:'Gradebook',exact:true}).click();await teacher.getByRole('combobox',{name:'Class',exact:true}).selectOption(String(sid));await expect(teacher.getByRole('table')).toContainText('100%');await shot(teacher,'12-teacher-gradebook');
 await student.goto(base+'/student');await expect(student.getByRole('heading',{level:1})).toBeVisible();await shot(student,'13-student-progress');await student.setViewportSize({width:390,height:844});await student.reload();await expect(student.getByRole('button',{name:'Expand dashboard sidebar'})).toBeVisible();await shot(student,'14-student-dashboard-mobile');
 fs.writeFileSync(out+'/workflow-results.json',JSON.stringify({status:'passed',course,section_id:sid,assignment_id:aid,assignmentTitle,answer,feedback,checks:['Teacher creates own class and enrolls two existing company students','Protected material upload and authenticated student download','Assignment publish on mobile','Failed draft request preserves text','Saved draft restored after reload','Student submits on mobile','Private message received by teacher','Failed grade request preserves feedback','Grade published and student sees exact feedback','Gradebook 100%','Mobile sidebar starts collapsed']},null,2));
 expect(fs.existsSync(out+'/runtime-errors.log') ? fs.readFileSync(out+'/runtime-errors.log','utf8').trim() : '').toBe('');
 await teacher.context().close();await student.context().close();
});
