import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import InstitutionPortalShell from '../components/InstitutionPortalShell';
import { institution, downloadInstitution, parseRoster } from '../services/institutionService';
import { clearAccountSession } from '../utils/institutionSession';

export default function CompanyWorkspace() {
  const [companies, setCompanies] = useState([]), [org, setOrg] = useState(''), [data, setData] = useState(null);
  const [tab, setTab] = useState('Overview'), [error, setError] = useState(''), [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [notice, setNotice] = useState('');
  const [name, setName] = useState(''), [kind, setKind] = useState('coaching');
  const [cohort, setCohort] = useState({ code: '', title: '', name: '', instructor_id: '', schedule: '', room: '' });
  const [email, setEmail] = useState(''), [inviteRole, setInviteRole] = useState('student'), [section, setSection] = useState(''), [roster, setRoster] = useState([]), [links, setLinks] = useState([]);
  const [enrollStudent, setEnrollStudent] = useState(''), [enrollSection, setEnrollSection] = useState('');
  async function loadCompanies() { setLoading(true); try { const rows = await institution('/companies'); setCompanies(rows); setOrg(current => current || String(rows.find(r => r.role === 'owner')?.id || '')); } catch(e) { setError(e.message); } finally { setLoading(false); } }
  async function loadOrg() { if (!org) return; const result = await institution(`/companies/${org}`); setData(result); }
  useEffect(() => { loadCompanies(); }, []);
  useEffect(() => { let active = true; setData(null); setError(''); setLinks([]); setRoster([]); setEmail(''); setInviteRole('student'); setCohort({code:'',title:'',name:'',instructor_id:'',schedule:'',room:''}); setSection(''); setEnrollSection(''); setEnrollStudent(''); if (org) institution(`/companies/${org}`).then(r => active && setData(r)).catch(e => active && setError(e.message)); return () => { active = false; }; }, [org]);
  async function act(work, message) { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await work(); if (org) await loadOrg(); setNotice(message); } catch(e) { setError(e.message); } finally { setBusy(false); } }
  const owners = companies.filter(c => c.role === 'owner');
  return <InstitutionPortalShell role="company" active="/company" company={data?.name || 'Company workspace'} title="Your learning business" subtitle="Set up your company, invite your people, and give every cohort a clear place to learn.">
    {error && <p role="alert" className="b2b-error">{error} <button className="ci-action" onClick={() => act(async () => { await loadCompanies(); if(org) await loadOrg(); }, 'Workspace refreshed.')}>Retry</button></p>}
    {notice && <p role="status" className="b2b-success">{notice}</p>}
    {loading && <p role="status">Loading your workspaces…</p>}
    {owners.length > 0 && <label className="b2b-field">Company<select disabled={busy} value={org} onChange={e => setOrg(e.target.value)}>{owners.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}
    {!loading && !owners.length && <section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><h2>Start with one cohort</h2><p>Create a company workspace, then add an instructor and invite your students. A new pilot has 25 seats for 30 days; it does not include a personal AI subscription.</p></section>}
    {data && <><nav className="b2b-tabs" aria-label="Company sections">{['Overview','Cohorts','People','Invitations','Activity'].map(t => <button className="ci-action" key={t} aria-pressed={tab === t} onClick={() => setTab(t)}>{t}</button>)}</nav>
      {tab === 'Overview' && <section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><h2>{data.name}</h2><p>{data.license.active} active people · {data.license.reserved} reserved invitations · {data.license.seat_limit} total seats</p><p>{data.license.plan} licence{data.license.expires_at ? ` · Ends ${new Date(data.license.expires_at).toLocaleDateString()}` : ''}. For more seats or a renewal, contact your Cerbyl operator. Personal AI usage is separate.</p><ol className="b2b-list"><li className="b2b-row">Invite your instructors in Invitations.</li><li className="b2b-row">Create a course and cohort in Cohorts.</li><li className="b2b-row">Invite students into that cohort.</li><li className="b2b-row">Your instructor publishes the first lesson and checkpoint.</li></ol><Link className="ci-action ci-action--primary" to="/educator/learning">Open learning studio</Link></section>}
      {tab === 'Cohorts' && <section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><h2>Courses & cohorts</h2><div className="b2b-list">{data.sections.map(s => <article className="b2b-row" key={s.id}><div className="b2b-row-header"><div><h3>{s.code} · {s.title}</h3><small>{s.name} · {s.students} students · {s.status}</small></div><button className="ci-action" disabled={busy} onClick={() => act(() => institution(`/companies/${org}/sections/${s.id}`, {status: s.status === 'active' ? 'archived' : 'active'}, 'PATCH'), 'Cohort updated.')}>{s.status === 'active' ? 'Archive cohort' : 'Restore cohort'}</button></div></article>)}</div>{!data.sections.length && <p className="b2b-empty">No cohorts yet. Create the first one below.</p>}
      <details className="b2b-detail" open={!data.sections.length}><summary>Create a cohort</summary><form className="b2b-form" onSubmit={e => { e.preventDefault(); act(async () => { await institution(`/companies/${org}/sections`, {...cohort, instructor_id: Number(cohort.instructor_id)}); setCohort({code:'',title:'',name:'',instructor_id:'',schedule:'',room:''}); }, 'Cohort created. Invite students next.'); }}>
        <div className="b2b-inline-fields"><label>Course code<input required pattern="[A-Za-z0-9_-]+" minLength={2} maxLength={30} value={cohort.code} onChange={e=>setCohort({...cohort,code:e.target.value})} placeholder="MATH101"/></label><label>Course title<input required minLength={3} maxLength={160} value={cohort.title} onChange={e=>setCohort({...cohort,title:e.target.value})} placeholder="Foundations of mathematics"/></label></div>
        <label>Cohort name<input required minLength={2} maxLength={80} value={cohort.name} onChange={e=>setCohort({...cohort,name:e.target.value})} placeholder="September evening group"/></label>
        <label>Instructor<select required value={cohort.instructor_id} onChange={e=>setCohort({...cohort,instructor_id:e.target.value})}><option value="">Choose instructor</option>{data.members.filter(m=>m.status==='active' && ['owner','educator'].includes(m.role)).map(m=><option key={m.id} value={m.user.id}>{m.user.display_name}</option>)}</select></label>
        <div className="b2b-inline-fields"><label>Schedule<input maxLength={120} value={cohort.schedule} onChange={e=>setCohort({...cohort,schedule:e.target.value})} placeholder="Tuesday & Thursday, 6 pm IST"/></label><label>Room or meeting location<input maxLength={80} value={cohort.room} onChange={e=>setCohort({...cohort,room:e.target.value})}/></label></div><button disabled={busy} className="ci-action ci-action--primary">{busy?'Saving…':'Create cohort'}</button></form></details></section>}
      {tab === 'People' && <section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><div className="b2b-bar"><h2>Your people</h2><button disabled={busy} className="ci-action" onClick={()=>act(()=>downloadInstitution(`/companies/${org}/roster.csv`,'company-roster.csv'),'Roster exported.')}>Export roster</button></div><p>Deactivating a person removes company access. After reactivation, add students back to their intended cohorts below.</p><div className="b2b-table"><table><thead><tr><th>Person</th><th>Role</th><th>Status</th><th>Access</th></tr></thead><tbody>{data.members.map(m=><tr key={m.id}><td>{m.user.display_name}<small>{m.user.email}</small></td><td>{m.role}</td><td>{m.status}</td><td>{m.role!=='owner' && <button disabled={busy} className="ci-action" onClick={()=>act(()=>institution(`/companies/${org}/members/${m.id}`,{status:m.status==='active'?'inactive':'active'},'PATCH'),'Member access updated.')}>{m.status==='active'?'Deactivate':'Reactivate'}</button>}</td></tr>)}</tbody></table></div>
        <form className="b2b-form" onSubmit={e=>{e.preventDefault();act(()=>institution(`/companies/${org}/sections/${enrollSection}/enrollments`,{student_id:Number(enrollStudent)}),'Student added to cohort.');}}><h3>Add an existing student to a cohort</h3><label>Student<select required value={enrollStudent} onChange={e=>setEnrollStudent(e.target.value)}><option value="">Choose student</option>{data.members.filter(m=>m.role==='student'&&m.status==='active').map(m=><option key={m.id} value={m.user.id}>{m.user.display_name}</option>)}</select></label><label>Cohort<select required value={enrollSection} onChange={e=>setEnrollSection(e.target.value)}><option value="">Choose cohort</option>{data.sections.filter(s=>s.status==='active').map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><button disabled={busy} className="ci-action ci-action--primary">Add to cohort</button></form></section>}
      {tab === 'Invitations' && <section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><h2>Invite your people</h2><p>Links are valid for seven days and work only with the invited email address. Copy and share them yourself; Cerbyl does not email these links automatically.</p><form className="b2b-form" onSubmit={e=>{e.preventDefault();act(async()=>{const result=await institution(`/companies/${org}/invitations`,{entries:(roster.length?roster:[email]).map(email=>({email,role:inviteRole,section_id:inviteRole==='student'&&section?Number(section):null}))});setLinks(result.invitations);setEmail('');setRoster([]);},'Invitation links created. Copy them below before leaving this company.');}}>
        <div className="b2b-inline-fields"><label>Role<select value={inviteRole} onChange={e=>setInviteRole(e.target.value)}><option value="student">Student</option><option value="educator">Teacher</option></select></label>{inviteRole==='student'&&<label>Cohort<select value={section} onChange={e=>setSection(e.target.value)}><option value="">Assign later</option>{data.sections.filter(s=>s.status==='active').map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label>}</div>
        <label>Email<input type="email" required={!roster.length} disabled={!!roster.length} value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label><label>Or import a roster CSV<input type="file" accept=".csv,text/csv" onChange={async e=>{try {const file=e.target.files[0];if(!file)return;if(file.size>100000)throw new Error('Roster files must be smaller than 100 KB.');setRoster(parseRoster(await file.text()));setError('');}catch(err){setRoster([]);setError(err.message);}}}/><small>One column named email, followed by one address per row. Maximum 200 rows.</small></label>{roster.length>0&&<p>{roster.length} addresses ready. <button type="button" className="ci-action" onClick={()=>setRoster([])}>Clear import</button></p>}<button disabled={busy} className="ci-action ci-action--primary">{busy?'Creating…':`Create invitations for ${data.name}`}</button></form>
        {links.map(l=><div className="b2b-row" key={l.email}><strong>{l.email}</strong><p className="b2b-source">{window.location.origin+l.path}</p><button className="ci-action" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.origin+l.path);setNotice('Invitation link copied.');}catch{setError('Copy the visible invitation link manually.');}}}>Copy invitation</button></div>)}
        <h3>Invitation history</h3>{data.invitations.map(i=><div className="b2b-row b2b-row-header" key={i.id}><div>{i.email}<small> · {i.role} · {i.status}</small></div>{i.status==='pending'&&<button disabled={busy} className="ci-action" onClick={()=>act(()=>institution(`/companies/${org}/invitations/${i.id}`,{},'DELETE'),'Invitation revoked.')}>Revoke</button>}</div>)}</section>}
      {tab==='Activity'&&<section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><h2>Company activity</h2>{data.audit.map(a=><article className="b2b-row" key={a.id}><h3>{a.action.replaceAll('_',' ')}</h3><p>{a.detail}</p><small>{new Date(a.created_at+'Z').toLocaleString()}</small></article>)}</section>}
    </>}
    {!loading&&<details className="b2b-panel" open={!owners.length}><summary className="b2b-link">Create another company workspace</summary><form className="b2b-form" onSubmit={e=>{e.preventDefault();act(async()=>{const result=await institution('/companies',{name,institution_type:kind});clearAccountSession();await loadCompanies();setOrg(String(result.id));setName('');},'Company created. Set up your first cohort.');}}><label>Company or learning centre name<input required minLength={3} maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>Organisation type<select value={kind} onChange={e=>setKind(e.target.value)}>{['coaching','training','school','university','company'].map(k=><option key={k}>{k}</option>)}</select></label><button disabled={busy} className="ci-action ci-action--primary">Create workspace</button></form></details>}
  </InstitutionPortalShell>;
}
