import AnswerFeedback from '../components/AnswerFeedback';
import useScopedAccountDraft from '../hooks/useScopedAccountDraft';
import { useEffect, useRef, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import InstitutionPortalShell from '../components/InstitutionPortalShell';
import StudentLearningPlan from '../components/StudentLearningPlan';
import { institution, downloadInstitution } from '../services/institutionService';
import { SubmissionDialog } from './StudentDashboard';

const emptyLesson = {title:'',objective:'',content:'',source_url:'',position:1,minutes:10,status:'draft'};
const emptyQuestion = () => ({prompt:'',options:['','','',''],correct_index:0,explanation:'',source:''});
const emptyCheckpoint = () => ({title:'',concept:'',questions:[emptyQuestion()]});
const confidenceLabels = ['Not sure yet','Getting there','Confident'];
const dateText = d => d ? new Date(/Z$|[+-]\d\d:\d\d$/.test(d)?d:d+'Z').toLocaleDateString() : 'No deadline';

function CheckpointPlayer({checkpoint, busy, onSubmit}) {
  const [answers,setAnswers] = useScopedAccountDraft(`checkpoint:${checkpoint.id}:answers`,{}), [confidence,setConfidence] = useScopedAccountDraft(`checkpoint:${checkpoint.id}:confidence`,{});
  const result = checkpoint.attempt;
  if (result) return <div className="b2b-row"><h3>{checkpoint.title} · {result.score_percent}%</h3><p>Your answers have been recorded. Review the explanation and source for each question.</p>{result.results.map((r,i)=><article className="b2b-row" key={i}><strong>{i+1}. {r.prompt}</strong><p>{r.is_correct?'Correct':'Needs another look'} · You chose: {r.options[r.chosen_index]}<br/>Expected: {r.options[r.correct_index]}</p><p>{r.explanation}</p><p className="b2b-source">Source: {r.source}</p>{!r.is_correct&&r.confidence===3&&<p>Your confidence was high. Explain what changed in your understanding when you review this with your teacher.</p>}</article>)}<AnswerFeedback resourceType="checkpoint_attempt" resourceId={result.id} sources={result.results.map(r=>({source_label:r.source}))}/></div>;
  return <form className="b2b-form" onSubmit={e=>{e.preventDefault();onSubmit(checkpoint.id,{answers:checkpoint.questions.map((_,i)=>Number(answers[i])),confidence:checkpoint.questions.map((_,i)=>Number(confidence[i]))});}}><h3>{checkpoint.title}</h3><small>Approved by your instructor · One recorded attempt · {checkpoint.questions.length} questions</small>{checkpoint.questions.map((q,i)=><fieldset className="b2b-question" key={i}><legend>{i+1}. {q.prompt}</legend>{q.options.map((option,j)=><label className="b2b-check" key={j}><input required type="radio" name={`checkpoint-${checkpoint.id}-${i}`} value={j} checked={answers[i]===String(j)} onChange={e=>setAnswers({...answers,[i]:e.target.value})}/>{option}</label>)}<label>How sure are you?<select required value={confidence[i]||''} onChange={e=>setConfidence({...confidence,[i]:e.target.value})}><option value="">Choose confidence</option>{confidenceLabels.map((l,i)=><option key={l} value={i+1}>{l}</option>)}</select></label></fieldset>)}<button disabled={busy} className="ci-action ci-action--primary">{busy?'Checking…':'Submit checkpoint'}</button></form>;
}

function FollowupItem({item, teacher, busy, act}) {
  const [response,setResponse] = useScopedAccountDraft(`followup:${item.id}:response`,''), [review,setReview] = useScopedAccountDraft(`followup:${item.id}:review`,'');
  return <article className="b2b-row"><div className="b2b-row-header"><h3>{item.title}</h3><span className="b2b-status">{item.status==='responded'?'Awaiting teacher review':item.status}</span></div><small>{teacher?item.student_name+' · ':''}{dateText(item.due_at)}</small><p>{item.instructions}</p>{item.student_response&&<><strong>Student response</strong><p>{item.student_response}</p></>}{item.review&&<><strong>Teacher feedback</strong><p>{item.review}</p></>}
    {!teacher&&item.status==='assigned'&&<form className="b2b-form" onSubmit={e=>{e.preventDefault();act(()=>institution(`/student/followups/${item.id}/respond`,{response}),'Response sent to your instructor.');}}><label>Explain your updated understanding<textarea rows={4} required minLength={20} maxLength={10000} value={response} onChange={e=>setResponse(e.target.value)}/></label><button disabled={busy} className="ci-action ci-action--primary">Send response</button></form>}
    {teacher&&item.status==='responded'&&<form className="b2b-form" onSubmit={e=>{e.preventDefault();act(()=>institution(`/educator/followups/${item.id}/review`,{review,status:'resolved'}),'Follow-up resolved. The student can see your feedback.');}}><label>Review and next step<textarea rows={3} required minLength={10} maxLength={5000} value={review} onChange={e=>setReview(e.target.value)}/></label><div className="b2b-bar"><button disabled={busy} className="ci-action ci-action--primary">Resolve follow-up</button><button disabled={busy||review.trim().length<10} type="button" className="ci-action" onClick={()=>act(()=>institution(`/educator/followups/${item.id}/review`,{review,status:'assigned'}),'Returned to the student for another response.')}>Ask for another response</button></div></form>}
  </article>;
}

function QualityReport({item,busy,act}) {
  const [resolution,setResolution]=useScopedAccountDraft(`report:${item.id}:resolution`,'');
  return <article className="b2b-row"><h3>{item.student_name} · {item.reason.replaceAll('_',' ')}</h3><p>{item.detail||'No additional detail supplied.'}</p><details className="b2b-detail"><summary>Inspect original questions and answers</summary>{(item.snapshot.answer||[]).map((q,i)=><div key={i} className="b2b-row"><strong>{q.prompt}</strong><p>Student: {q.options[q.chosen_index]}<br/>Answer key: {q.options[q.correct_index]}</p><p>{q.explanation}</p><small>{q.source}</small></div>)}</details>{item.status==='resolved'?<p>Published correction: {item.resolution}</p>:<form className="b2b-form" onSubmit={async e=>{e.preventDefault();if(await act(()=>institution(`/educator/checkpoint-reports/${item.id}/resolve`,{resolution}),'Correction published to the student.'))setResolution('');}}><label>Correction or explanation<textarea required minLength={10} maxLength={5000} rows={4} value={resolution} onChange={e=>setResolution(e.target.value)}/></label><button disabled={busy} className="ci-action ci-action--primary">Publish correction</button></form>}</article>;
}

export default function InstitutionLearning({role}) {
  const teacher = role==='educator';
  const [params,setParams] = useSearchParams();
  const [dashboard,setDashboard] = useState(null), [section,setSection] = useState(params.get('section')||''), [data,setData] = useState(null), [brief,setBrief] = useState(null), [plan,setPlan] = useState(null);
  const [tab,setTab] = useState(params.get('view')||(teacher?'Lessons':'My plan')), [loading,setLoading] = useState(true), [busy,setBusy] = useState(false), [error,setError] = useState(''), [notice,setNotice] = useState('');
  const [lesson,setLesson] = useScopedAccountDraft(`cohort:${section}:lesson-editor`,null), [checkpoint,setCheckpoint] = useScopedAccountDraft(`cohort:${section}:checkpoint-editor`,null), [followup,setFollowup] = useScopedAccountDraft(`cohort:${section}:followup-editor`,null), [confidence,setConfidence] = useState({}), [assignment,setAssignment] = useState(null);
  const sectionRef = useRef(section); sectionRef.current = section;
  const highlighted = params.get('item');
  const sections = teacher ? (dashboard?.class_health||[]).map(c=>({id:c.section_id,title:c.course_title,code:c.course_code,name:c.section_name,company:c.organization_name})) : (dashboard?.courses||[]).map(c=>({id:c.section_id,title:c.title,code:c.code,name:c.section_name,company:c.organization_name}));
  async function loadDashboard() { setLoading(true); try { const d=await institution(`/${role}/dashboard`);setDashboard(d);const first=teacher?d.class_health?.[0]?.section_id:d.courses?.[0]?.section_id;setSection(s=>s||String(first||''));if(!teacher)setPlan(await institution('/student/plan')); }catch(e){setError(e.message);}finally{setLoading(false);} }
  async function refresh() { const sid=sectionRef.current; if(!sid)return; const d=await institution(`/sections/${sid}/learning`);if(sectionRef.current!==sid)return;setData(d);if(teacher){const b=await institution(`/educator/sections/${sid}/briefing`);if(sectionRef.current===sid)setBrief(b);}else setPlan(await institution('/student/plan')); }
  useEffect(()=>{loadDashboard();},[role]);
  useEffect(()=>{let active=true;setData(null);setBrief(null);setNotice('');setError('');if(section){institution(`/sections/${section}/learning`).then(d=>active&&setData(d)).catch(e=>active&&setError(e.message));if(teacher)institution(`/educator/sections/${section}/briefing`).then(d=>active&&setBrief(d)).catch(e=>active&&setError(e.message));}return()=>{active=false;};},[section,teacher]);
  useEffect(()=>{if(data&&highlighted){document.getElementById(`learning-${highlighted}`)?.scrollIntoView({block:'center',behavior:'auto'});}},[data,highlighted,tab]);
  async function act(work,message) {if(busy)return;setBusy(true);setError('');setNotice('');try{await work();await refresh();setNotice(message);return true;}catch(e){setError(e.message);return false;}finally{setBusy(false);}}
  function openTask(t) { if(t.type==='assignment'){const row=dashboard.assignments.find(a=>a.id===t.id);if(row)setAssignment(row);else setError('This assignment could not be opened. Refresh your classroom and try again.');return;} const nextTab=t.type==='lesson'?'Lessons':t.type==='checkpoint'?'Checkpoints':'Follow-up';setSection(String(t.section_id));setTab(nextTab);setParams({section:String(t.section_id),view:nextTab,item:String(t.id)}); }
  useEffect(()=>{
    const allowed=teacher?['Lessons','Checkpoints','Teaching signals','Follow-up','Quality reports']:['My plan','Lessons','Checkpoints','Follow-up','Progress'];
    const desired=params.get('view');
    setTab(allowed.includes(desired)?desired:(teacher?'Lessons':'My plan'));
    const desiredSection=params.get('section');
    if(desiredSection && sections.some(s=>String(s.id)===desiredSection))setSection(desiredSection);
  },[params.toString(),dashboard]);
  const tabs=teacher?['Lessons','Checkpoints','Teaching signals','Follow-up','Quality reports']:['My plan','Lessons','Checkpoints','Follow-up','Progress'];
  const studentTabLabels = {'My plan':'Today',Lessons:'Lessons',Checkpoints:'Practice','Follow-up':'From your teacher',Progress:'Progress'};
  const learningNav = <nav className={teacher?'b2b-tabs':'b2b-learning-nav'} aria-label="Learning workspace">{tabs.map(t=><button key={t} className={teacher?'ci-action':undefined} aria-pressed={tab===t} onClick={()=>{setTab(t);setParams({section,view:t});}}>{teacher?t:studentTabLabels[t]}</button>)}</nav>;
  return <InstitutionPortalShell user={dashboard?.user} className={teacher?'':'b2b-student-learning'} role={role} active={`/${role}/learning`} company={data?.section?.organization_name||sections.find(s=>String(s.id)===section)?.company||dashboard?.organization?.name||'Company learning'} title={teacher?'Learning studio':'My learning'} subtitle={teacher?'Publish a clear lesson, check understanding, and turn the answers into useful follow-up.':'See what’s next, finish your work, and get help when you need it.'}>
    {error&&<p role="alert" className="b2b-error">{error} <button className="ci-action" onClick={()=>act(async()=>{await loadDashboard();await refresh();},'Refreshed.')}>Try again</button></p>}{notice&&<p role="status" className="b2b-success">{notice}</p>}
    {loading&&<p role="status">Loading your classroom…</p>}
    {!loading&&!sections.length&&<section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><h2>Your classroom starts here</h2><p>{teacher?'Ask your company owner to assign you a cohort, or create your own company workspace.':'Accept your company invitation, then ask your owner to add you to a cohort.'}</p><Link className="ci-action ci-action--primary" to={teacher?'/company':'/join-company'}>{teacher?'Company workspace':'Accept invitation'}</Link></section>}
    {!!sections.length&&<>
    {!teacher&&learningNav}
    {(teacher||tab!=='My plan')&&<div className="b2b-bar b2b-learning-context"><label className="b2b-field">{teacher?'Active cohort':'Class'}<select disabled={busy} value={section} onChange={e=>{setSection(e.target.value);setParams({section:e.target.value,view:tab});}}>{sections.map(s=><option key={s.id} value={s.id}>{teacher?s.code:s.title} · {s.name} · {s.company}</option>)}</select></label><span className="b2b-spacer"/><Link className="ci-action" to={teacher?'/educator/classes':'/student/library'}>{teacher?'Materials & classroom':'Class materials'}</Link>{teacher&&<button disabled={busy} className="ci-action" onClick={()=>act(()=>downloadInstitution(`/educator/sections/${section}/grades.csv`,'cohort-grades.csv'),'Grades exported.')}>Export grades</button>}</div>}
    {teacher&&learningNav}
    {!data&&!error&&tab!=='My plan'&&<p role="status">Loading this cohort…</p>}
    {tab==='My plan'&&plan&&<StudentLearningPlan plan={plan} sections={sections} openTask={openTask}/>}
    {data&&tab==='Progress'&&<section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><h2>Your cohort progress</h2><p>{data.lessons.filter(l=>l.completion).length} of {data.lessons.length} lessons marked complete · {data.checkpoints.filter(c=>c.attempt).length} of {data.checkpoints.length} checkpoints submitted · {data.followups.filter(f=>f.status==='resolved').length} follow-ups resolved.</p><p>Lesson completion and confidence are your check-ins. Checkpoint scores use your teacher’s answer keys. Assignment scores and feedback are published by your teacher.</p><h3>Checkpoint results</h3>{data.checkpoints.filter(c=>c.attempt).map(c=><div className="b2b-row" key={c.id}><strong>{c.title} · {c.attempt.score_percent}%</strong><div className="b2b-actions"><button className="ci-action" onClick={()=>{setTab('Checkpoints');setParams({section,view:'Checkpoints',item:String(c.id)});}}>Review answers</button></div></div>)}<h3>Assignments & feedback</h3>{(dashboard?.assignments||[]).filter(a=>String(a.section_id)===section).map(a=><article className="b2b-row" key={a.id}><h3>{a.title}</h3><small>{a.status.replaceAll('_',' ')} · {a.score===null||a.score===undefined?'Awaiting grade':`${a.score}/${a.points_possible}`}</small>{a.feedback&&<p>{a.feedback}</p>}<button className="ci-action" onClick={()=>setAssignment(a)}>Open work & history</button></article>)}</section>}
    {data&&tab==='Lessons'&&<section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><div className="b2b-bar"><h2>Lessons</h2><span className="b2b-spacer"/>{teacher&&<button className="ci-action ci-action--primary" disabled={!!lesson} onClick={()=>setLesson({...emptyLesson,position:data.lessons.length+1})}>Create lesson</button>}</div><p>{teacher?'Keep lessons focused on one outcome. Save a draft, then publish when it is ready.':'Work through the lessons in order. Your confidence check-in helps your teacher understand where to help.'}</p>
      {lesson&&<form className="b2b-form" onSubmit={e=>{e.preventDefault();act(async()=>{const body={...lesson,source_url:lesson.source_url||null,position:Number(lesson.position),minutes:Number(lesson.minutes)};await institution(lesson.id?`/educator/lessons/${lesson.id}`:`/educator/sections/${section}/lessons`,body,lesson.id?'PUT':'POST');setLesson(null);},'Lesson saved.');}}><label>Lesson title<input required minLength={3} maxLength={180} value={lesson.title} onChange={e=>setLesson({...lesson,title:e.target.value})}/></label><label>What will students be able to do?<input required minLength={3} maxLength={500} value={lesson.objective} onChange={e=>setLesson({...lesson,objective:e.target.value})}/></label><label>Lesson content<textarea rows={9} required minLength={20} maxLength={30000} value={lesson.content} onChange={e=>setLesson({...lesson,content:e.target.value})}/></label><label>Source or reading link (optional)<input type="url" maxLength={500} value={lesson.source_url||''} onChange={e=>setLesson({...lesson,source_url:e.target.value})}/></label><div className="b2b-inline-fields"><label>Position<input type="number" min={1} max={1000} required value={lesson.position} onChange={e=>setLesson({...lesson,position:e.target.value})}/></label><label>Estimated minutes<input type="number" min={1} max={180} required value={lesson.minutes} onChange={e=>setLesson({...lesson,minutes:e.target.value})}/></label></div><label>Visibility<select value={lesson.status} onChange={e=>setLesson({...lesson,status:e.target.value})}><option value="draft">Draft — only you can see it</option><option value="published">Published — visible to students</option><option value="archived">Archived — hidden from students</option></select></label><div className="b2b-bar"><button disabled={busy} className="ci-action ci-action--primary">Save lesson</button><button type="button" className="ci-action" disabled={busy} onClick={()=>setLesson(null)}>Cancel</button></div></form>}
      {!data.lessons.length&&<p className="b2b-empty">{teacher?'Create your first lesson above.':'Your teacher has not published lessons yet.'}</p>}
      {data.lessons.map(l=><article id={`learning-${l.id}`} className="b2b-row" key={l.id}><div className="b2b-row-header"><h3>{l.position}. {l.title}</h3><span className="b2b-status">{teacher?l.status:l.completion?'Completed':'Ready'} · {l.minutes} min</span></div><p>{l.objective}</p><details className="b2b-detail" open={highlighted===String(l.id)}><summary>Read lesson</summary><div className="b2b-body">{l.content}</div>{l.source_url&&<p><a className="b2b-source" href={l.source_url} target="_blank" rel="noreferrer">Open source reading ↗</a></p>}
        {!teacher&&<form className="b2b-form" onSubmit={e=>{e.preventDefault();act(()=>institution(`/student/lessons/${l.id}/complete`,{confidence:Number(confidence[l.id]||l.completion?.confidence)}),'Lesson progress saved.');}}><label>How confident do you feel?<select required value={confidence[l.id]||l.completion?.confidence||''} onChange={e=>setConfidence({...confidence,[l.id]:e.target.value})}><option value="">Choose confidence</option>{confidenceLabels.map((c,i)=><option key={c} value={i+1}>{c}</option>)}</select></label><small>This is your check-in, not a test score.</small><button disabled={busy} className="ci-action ci-action--primary">{l.completion?'Update check-in':'Mark lesson complete'}</button></form>}</details>{teacher&&<button className="ci-action" disabled={!!lesson} onClick={()=>setLesson({...l,source_url:l.source_url||''})}>Edit lesson</button>}</article>)}
    </section>}
    {data&&tab==='Checkpoints'&&<section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><div className="b2b-bar"><h2>Check understanding</h2><span className="b2b-spacer"/>{teacher&&<button className="ci-action ci-action--primary" disabled={!!checkpoint} onClick={()=>setCheckpoint(emptyCheckpoint())}>Create checkpoint</button>}</div><p>{teacher?'Draft questions, inspect every answer key and source, then approve. Published checkpoints stay fixed to preserve student results.':'Your teacher reviewed these questions. Choose an answer and how sure you are before submitting.'}</p>
      {checkpoint&&<form className="b2b-form" onSubmit={e=>{e.preventDefault();act(async()=>{await institution(checkpoint.id?`/educator/checkpoints/${checkpoint.id}`:`/educator/sections/${section}/checkpoints`,checkpoint,checkpoint.id?'PUT':'POST');setCheckpoint(null);},'Checkpoint saved as a draft. Review its answer keys, then approve it below.');}}><label>Checkpoint title<input required minLength={3} maxLength={180} value={checkpoint.title} onChange={e=>setCheckpoint({...checkpoint,title:e.target.value})}/></label><label>Concept<input required minLength={2} maxLength={120} value={checkpoint.concept} onChange={e=>setCheckpoint({...checkpoint,concept:e.target.value})}/></label>{checkpoint.questions.map((q,i)=>{function change(field,value){setCheckpoint({...checkpoint,questions:checkpoint.questions.map((q,j)=>j===i?{...q,[field]:value}:q)});}return <fieldset className="b2b-question" key={i}><legend>Question {i+1}</legend><label>Prompt<textarea required minLength={5} maxLength={2000} value={q.prompt} onChange={e=>change('prompt',e.target.value)}/></label>{q.options.map((o,j)=><label key={j}>Option {String.fromCharCode(65+j)}<input required maxLength={1000} value={o} onChange={e=>change('options',q.options.map((o,k)=>k===j?e.target.value:o))}/></label>)}<label>Correct answer<select value={q.correct_index} onChange={e=>change('correct_index',Number(e.target.value))}>{q.options.map((_,j)=><option key={j} value={j}>Option {String.fromCharCode(65+j)}</option>)}</select></label><label>Explanation<textarea required minLength={10} maxLength={3000} value={q.explanation} onChange={e=>change('explanation',e.target.value)}/></label><label>Source reference<input required minLength={3} maxLength={1000} value={q.source} onChange={e=>change('source',e.target.value)} placeholder="Lesson title, document page, or source URL"/></label>{checkpoint.questions.length>1&&<button type="button" className="ci-action" onClick={()=>setCheckpoint({...checkpoint,questions:checkpoint.questions.filter((_,j)=>i!==j)})}>Remove question {i+1}</button>}</fieldset>;})}<div className="b2b-bar"><button disabled={checkpoint.questions.length>=20} type="button" className="ci-action" onClick={()=>setCheckpoint({...checkpoint,questions:[...checkpoint.questions,emptyQuestion()]})}>Add question</button><button disabled={busy} className="ci-action ci-action--primary">Save draft</button><button disabled={busy} type="button" className="ci-action" onClick={()=>setCheckpoint(null)}>Cancel</button></div></form>}
      {!data.checkpoints.length&&<p className="b2b-empty">{teacher?'Create a short checkpoint to see what students understand.':'Your teacher has not published a checkpoint yet.'}</p>}
      {data.checkpoints.map(c=><article className="b2b-row" id={`learning-${c.id}`} key={c.id}>{teacher?<><div className="b2b-row-header"><h3>{c.title}</h3><span className="b2b-status">{c.status} · {c.questions.length} questions</span></div><details className="b2b-detail"><summary>Review questions, answers & sources</summary>{c.questions.map((q,i)=><div className="b2b-row" key={i}><strong>{i+1}. {q.prompt}</strong><ol type="A">{q.options.map((o,j)=><li key={j}>{o}{q.correct_index===j?' — correct':''}</li>)}</ol><p>{q.explanation}</p><p className="b2b-source">Source: {q.source}</p></div>)}{c.status==='draft'&&<div className="b2b-bar"><button disabled={busy||!!checkpoint} className="ci-action" onClick={()=>setCheckpoint({id:c.id,title:c.title,concept:c.concept,questions:c.questions})}>Edit draft</button><button disabled={busy} className="ci-action ci-action--primary" onClick={()=>act(()=>institution(`/educator/checkpoints/${c.id}/approve`,{}),'Checkpoint approved and published to your students.')}>I reviewed this — publish</button></div>}</details>{c.status==='published'&&<div className="b2b-bar"><button disabled={busy||!!checkpoint} className="ci-action" onClick={()=>setCheckpoint({title:`${c.title.slice(0,160)} (revised)`,concept:c.concept,questions:c.questions})}>Create revised copy</button><button disabled={busy} className="ci-action" onClick={()=>act(()=>institution(`/educator/checkpoints/${c.id}/archive`,{}),'Checkpoint retired. Existing results are preserved.')}>Retire checkpoint</button></div>}</>:<CheckpointPlayer checkpoint={c} busy={busy} onSubmit={(id,body)=>act(()=>institution(`/student/checkpoints/${id}/submit`,body),'Your checkpoint was graded and saved.')}/>}</article>)}
    </section>}
    {teacher&&tab==='Teaching signals'&&brief&&<section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><h2>Your weekly briefing</h2><p>{brief.participating_students} of {brief.students} students completed {brief.recent_attempts} checkpoint attempts in the last seven days. {brief.waiting_for_review} follow-ups await review; {brief.resolved_followups} were resolved this week.</p><p>{brief.basis}</p><h3>Students who asked for reinforcement</h3>{(brief.lesson_checkins||[]).map((c,i)=><div className="b2b-row" key={i}><strong>{c.student_name}</strong><p>{c.lesson} · Student check-in: not sure yet.</p></div>)}{!brief.lesson_checkins?.length&&<p>No low-confidence lesson check-ins yet.</p>}<h3>Answers to revisit</h3>{!brief.evidence.length&&<p className="b2b-empty">No incorrect checkpoint answers have been recorded yet.</p>}{brief.evidence.map((e,i)=><article className="b2b-row" key={i}><div className="b2b-row-header"><h3>{e.student_name} · {e.concept}</h3><span className="b2b-status">{e.signal}</span></div><p>{e.question}<br/>Student answered: {e.answer}<br/>Expected: {e.expected}</p><small>Answered {dateText(e.submitted_at)} · Source: {e.source}</small><div className="b2b-actions"><button className="ci-action ci-action--primary" onClick={()=>{setFollowup({student_id:e.student_id,title:`Revisit ${e.concept}`,instructions:`Review the source: ${e.source}\nExplain why “${e.expected}” is the appropriate answer to: ${e.question}\nThen give a new example in your own words.`,checkpoint_attempt_id:e.attempt_id,due_at:''});setTab('Follow-up');setParams({section,view:'Follow-up'});}}>Assign a next step</button></div></article>)}<h3>Missing work</h3>{brief.missing_work.map((m,i)=><div key={i} className="b2b-row"><strong>{m.student_name}</strong><p>{m.assignment}</p><button className="ci-action" onClick={()=>{setFollowup({student_id:m.student_id,title:`Catch up: ${m.assignment}`,instructions:`Please complete ${m.assignment}. If you are stuck, explain which part is difficult and what you have tried so we can work through it together.`,due_at:''});setTab('Follow-up');setParams({section,view:'Follow-up'});}}>Create catch-up step</button></div>)}{!brief.missing_work.length&&<p>No overdue missing assignments.</p>}</section>}
    {data&&teacher&&tab==='Quality reports'&&<section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><h2>Questions students flagged</h2><p>Review the original question and answer before publishing a correction. Retire an incorrect checkpoint and publish a revised copy; original attempt scores remain in the record.</p>{!data.reports?.length&&<p>No checkpoint reports in this cohort.</p>}{(data.reports||[]).map(r=><QualityReport key={r.id} item={r} busy={busy} act={act}/>)}</section>}
    {data&&tab==='Follow-up'&&<section className="b2b-panel"><div className="ci-tile-texture" aria-hidden="true"/><div className="b2b-bar"><h2>{teacher?'Close the learning loop':'Your teacher’s next steps'}</h2>{teacher&&<button className="ci-action ci-action--primary" disabled={!!followup} onClick={()=>setFollowup({student_id:'',title:'',instructions:'',due_at:''})}>Assign follow-up</button>}</div><p>{teacher?'Choose a student, give a concrete next step, then review their response before resolving it.':'Respond in your own words. Your teacher will review your response and tell you what to do next.'}</p>
    {teacher&&followup&&<form className="b2b-form" onSubmit={e=>{e.preventDefault();act(async()=>{await institution(`/educator/sections/${section}/followups`,{...followup,student_id:Number(followup.student_id),due_at:followup.due_at?new Date(followup.due_at).toISOString():null});setFollowup(null);},'Follow-up assigned privately to the student.');}}><label>Student<select required value={followup.student_id} onChange={e=>setFollowup({...followup,student_id:e.target.value,checkpoint_attempt_id:null})}><option value="">Choose student</option>{data.roster.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Title<input required minLength={3} maxLength={180} value={followup.title} onChange={e=>setFollowup({...followup,title:e.target.value})}/></label><label>What should the student do?<textarea rows={6} required minLength={20} maxLength={5000} value={followup.instructions} onChange={e=>setFollowup({...followup,instructions:e.target.value})}/></label><label>Due date (your local time, optional)<input type="datetime-local" value={followup.due_at} onChange={e=>setFollowup({...followup,due_at:e.target.value})}/></label><div className="b2b-bar"><button disabled={busy} className="ci-action ci-action--primary">Assign privately</button><button disabled={busy} type="button" className="ci-action" onClick={()=>setFollowup(null)}>Cancel</button></div></form>}
    {!data.followups.length&&<p className="b2b-empty">No follow-up tasks in this cohort yet.</p>}{data.followups.map(f=><div id={`learning-${f.id}`} key={f.id}><FollowupItem item={f} teacher={teacher} busy={busy} act={act}/></div>)}
    </section>}
    </>}
    {assignment&&<SubmissionDialog assignment={assignment} onClose={()=>setAssignment(null)} onSubmitted={()=>{setAssignment(null);loadDashboard();refresh();}}/>}
  </InstitutionPortalShell>;
}
