import { useEffect, useState } from 'react';
import { productRequest } from '../services/productService';
import '../pages/ProductFlows.css';
function ReportReview({ row, onResolved }) {
  const [resolution, setResolution] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { await productRequest(`/product/admin/answer-reports/${row.id}/resolve`, { method: 'POST', body: JSON.stringify({ resolution }) }); onResolved(row.id); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <details><summary>Report #{row.id} · {row.reason.replaceAll('_', ' ')}</summary><p><strong>Question:</strong> {row.snapshot.question}</p><p><strong>Original answer:</strong> {row.snapshot.answer}</p>{row.snapshot.student_answer && <p>Student answer: {row.snapshot.student_answer}</p>}<p>{row.detail}</p><form onSubmit={submit}><label>Correction or explanation for the learner<textarea required minLength={10} maxLength={5000} value={resolution} onChange={e => setResolution(e.target.value)} /></label><p className="flow-muted">Provide the corrected answer and a verifiable reference, or explain why the original is valid. This records a visible correction; it does not rewrite grades or the source question.</p>{error && <p role="alert" className="flow-error">{error}</p>}<button disabled={busy || resolution.trim().length < 10}>{busy ? 'Saving…' : 'Publish correction to learner'}</button></form></details>;
}
export default function ProductAdmin() {
  const [metrics, setMetrics] = useState(null); const [reports, setReports] = useState([]); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { setBusy(true); setError(''); try { const [m, r] = await Promise.all([productRequest('/product/admin/metrics'), productRequest('/product/admin/answer-reports')]); setMetrics(m); setReports(r); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  useEffect(() => { load(); }, []);
  return <section className="learning-flow flow-panel"><div className="flow-topline"><h2>Pilot funnel, costs & answer quality</h2><button onClick={load} disabled={busy}>{busy ? 'Loading…' : 'Refresh pilot data'}</button></div>{error && <p role="alert" className="flow-error">{error}</p>}{metrics && <><p>Last {metrics.days} days · Tracking starts when this release is deployed.</p><div className="flow-table-wrap"><table><caption>Observed funnel events</caption><thead><tr><th>Event</th><th>Source</th><th>Count</th><th>Accounts</th><th>Browsers</th></tr></thead><tbody>{metrics.events.map(row => <tr key={`${row.name}-${row.origin}`}><td>{row.name.replaceAll('_', ' ')}</td><td>{row.origin}</td><td>{row.events}</td><td>{row.users}</td><td>{row.visitors}</td></tr>)}</tbody></table></div>{metrics.events.length === 0 && <p>No events recorded yet.</p>}<p>Returned to practice on another day within 7 days: <strong>{metrics.practice_return_7d.returned_users}/{metrics.practice_return_7d.eligible_users}</strong> eligible accounts.</p><h3>Sample attribution</h3><p>{metrics.sample_funnel.sample_browsers} sample browsers → {metrics.sample_funnel.linked_activated_accounts} activated accounts → {metrics.sample_funnel.linked_practising_accounts} practising accounts; {metrics.sample_funnel.linked_paying_accounts} paying accounts. Browser attribution is incomplete across devices.</p><h3>AI cost coverage</h3>{metrics.ai_costs.available ? <p>US${metrics.ai_costs.estimated_usd.toFixed(4)} estimated across {metrics.ai_costs.priced_calls} priced calls. <strong>{metrics.ai_costs.unpriced_calls} calls have no configured price.</strong></p> : <p className="flow-error">Usage cost data could not be read. No cost conclusion is available.</p>}<h3>Payment receipts</h3>{metrics.receipts.length ? metrics.receipts.map(row => <p key={row.currency}>{row.currency.toUpperCase()}: {row.amount_minor.toLocaleString()} minor currency units</p>) : <p>No payment receipts recorded in this window.</p>}<p className="flow-muted">{metrics.notes}</p></>}<h3>Answer review queue</h3><p>Open reports (up to 200, oldest first). Refresh after clearing these to load the next batch.</p>{reports.map(row => <ReportReview key={row.id} row={row} onResolved={id => setReports(reports.filter(r => r.id !== id))} />)}{!reports.length && !busy && !error && <p>No open reports.</p>}</section>;
}
